//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ProjectStart_DBEntities : DbContext
    {
        public ProjectStart_DBEntities()
            : base("name=ProjectStart_DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<Period> Periods { get; set; }
        public virtual DbSet<Product_Brand> Product_Brand { get; set; }
        public virtual DbSet<Product_Categorys> Product_Categorys { get; set; }
        public virtual DbSet<Product_Selected_Category> Product_Selected_Category { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<Recive_Vendor_Products> Recive_Vendor_Products { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Vendor_Groups> Vendor_Groups { get; set; }
        public virtual DbSet<Vendor_Products> Vendor_Products { get; set; }
        public virtual DbSet<Vendor_Selected_Group> Vendor_Selected_Group { get; set; }
        public virtual DbSet<Vendor> Vendors { get; set; }
    }
}
