//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int OrderID { get; set; }
        public int UserID { get; set; }
        public int ProductID { get; set; }
        public int PeriodIDRef { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<bool> IsFinaly { get; set; }
    
        public virtual Period Period { get; set; }
        public virtual Product Product { get; set; }
        public virtual User User { get; set; }
    }
}
